<div class="modal-header">
    <button type="button" class="close" ng-click="cancel()">&times;</button>
    <h4 class="modal-title">Key Bind Options</h4>
</div>
<div class="modal-body">
    <form id="mkgKeyBindOptionsForm" name="mkgKeyBindOptionsForm" class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-sm-4">Key to Bind</label>
            <div class="col-sm-8">
                <div class="form-control" disabled>
                    <pre class="label label-default">{{ bindOptions.keyToBind }}</pre>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="mkgPrimaryWeaponSelect" class="control-label col-sm-4">Primary Weapon</label>
            <div class="col-sm-8">
                <ui-select id="mkgPrimaryWeaponSelect" name="mkgPrimaryWeaponSelect" theme="bootstrap" ng-model="bindOptions.primaryWeapon">
                    <ui-select-match placeholder="None">{{$select.selected.name}}</ui-select-match>
                    <ui-select-choices repeat="weapon.bind as weapon in (primaryWeapons | filter: $select.search) track by weapon.bind"
                                       group-by="'weaponGroup'">
                        <span ng-bind-html="weapon.name | highlight: $select.search"></span>
                    </ui-select-choices>
                </ui-select>
            </div>
        </div>
        <div class="form-group">
            <label for="mkgSecondaryWeaponSelect" class="control-label col-sm-4">Secondary Weapon</label>
            <div class="col-sm-8">
                <ui-select id="mkgSecondaryWeaponSelect" name="mkgSecondaryWeaponSelect" theme="bootstrap" ng-model="bindOptions.secondaryWeapon">
                    <ui-select-match placeholder="None">{{$select.selected.name}}</ui-select-match>
                    <ui-select-choices repeat="weapon.bind as weapon in (secondaryWeapons | filter: $select.search) track by weapon.bind"
                                       group-by="'weaponGroup'">
                        <span ng-bind-html="weapon.name | highlight: $select.search"></span>
                    </ui-select-choices>
                </ui-select>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-4">Gear</label>
            <div class="col-sm-8">
                <div ng-repeat="gearItem in gear" class="checkbox">
                    <label>
                        <input name="mkgGear[]"
                               type="checkbox"
                               value="{{ gearItem.bind }}"
                               ng-checked="bindOptions.gear.indexOf(gearItem.bind) > -1"
                               ng-click="toggleGearSelection(gearItem.bind)" /> {{ gearItem.name }}
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-4">Grenades</label>
            <div class="col-sm-8">
                <div ng-repeat="grenade in grenades" class="checkbox">
                    <label>
                        <input name="mkgGrenades[]"
                               type="checkbox"
                               value="{{ grenade.bind }}"
                               ng-checked="bindOptions.grenades.indexOf(grenade.bind) > -1"
                               ng-click="toggleGrenadeSelection(grenade.bind)"
                               ng-disabled="allowExtraGrenade(grenade.bind) && hasExtraGrenadeSelection(grenade.bind)" />
                        {{ grenade.name }}
                    </label>
                    <label ng-show="allowExtraGrenade(grenade.bind)">
                        ( <input name="mkgExtraFlash"
                                 type="checkbox"
                                 class="checkbox-extra"
                                 value="{{ grenade.bind }}"
                                 ng-checked="hasExtraGrenadeSelection(grenade.bind)"
                                 ng-click="toggleExtraGrenadeSelection(grenade.bind)" />
                        <span class="checkbox-inline-inline-label">&times; 2</span> )
                    </label>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-info" ng-click="save()">Save</button>
    <button type="button" class="btn btn-default" ng-click="cancel()">Cancel</button>
    <button type="button" class="btn btn-warning" ng-click="clear()">Clear</button>
</div>
