<div class="modal-header">
    <button type="button" class="close" ng-click="cancel()">&times;</button>
    <h4 class="modal-title">Save Binds</h4>
</div>
<div class="modal-body">
    <form id="mkgSaveBindsForm" name="mkgSaveBindsForm" class="form-horizontal">
        <div class="form-group has-feedback" ng-class="{ 'has-error': submitted && mkgSaveBindsForm.mkgBuyBindsSaveAsNameTxtBox.$invalid }">
            <label class="control-label col-sm-4" for="mkgBuyBindsSaveAsNameTxtBox">Save As:</label>
            <div class="col-sm-8">
                <input id="mkgBuyBindsSaveAsNameTxtBox" name="mkgBuyBindsSaveAsNameTxtBox" type="text"
                       ng-model="buyBindsSaveAsName" class="form-control" placeholder="My Custom Buynds"
                       ng-pattern="/^[a-zA-Z0-9 !@#$%\^&*)(+=._\[\]{}:;',.<>?/-]+$/" ng-maxlength="25" maxlength="25" required
                       ng-class="{ 'has-error': submitted && mkgSaveBindsForm.mkgBuyBindsSaveAsNameTxtBox.$invalid }">
                <span class="glyphicon glyphicon-remove form-control-feedback"
                      ng-if="submitted && mkgSaveBindsForm.mkgBuyBindsSaveAsNameTxtBox.$invalid"></span>
                <p class="help-block" ng-show="submitted && mkgSaveBindsForm.mkgBuyBindsSaveAsNameTxtBox.$invalid"><span class="glyphicon glyphicon-remove"></span> Invalid bind name!</p>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-4" for="mkgBuyBindsSaveInSlotSelect">In Slot:</label>
            <div class="col-sm-8">
                <select id="mkgBuyBindsSaveInSlotSelect" name="mkgBuyBindsSaveInSlotSelect" class="form-control"
                        ng-model="buyBindsSaveInSlot" required>
                    <option ng-repeat="saveSlot in buyBindsSaveSlots"
                            value="{{ saveSlot }}"
                            ng-selected="buyBindsSaveInSlot == saveSlot">{{ saveSlot }}</option>
                </select>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-success" ng-click="save()">Save Binds <span class="glyphicon glyphicon-floppy-disk"></span></button>
    <button type="button" class="btn btn-default" ng-click="cancel()">Cancel</button>
</div>
