<div class="modal-header">
    <button type="button" class="close" ng-click="cancel()">&times;</button>
    <h4 class="modal-title">Key Bind Options</h4>
</div>
<div class="modal-body">
    <div class="form-group">
        <label for="mkgPrimaryWeaponSelect" class="control-label col-sm-4">Primary Weapon</label>
        <div class="col-sm-8">
            <select id="mkgPrimaryWeaponSelect" name="mkgPrimaryWeaponSelect" class="form-control" ng-model="bindOptions.primaryWeapon">
                <option value="">None</option>
                <optgroup ng-repeat="weaponGroup in primaryWeapons.weaponGroups" label="{{ weaponGroup.name }}">
                    <option ng-repeat="primary in weaponGroup.weapons" value="{{ primary.bind }}">{{ primary.name }}</option>
                </optgroup>
            </select>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-info" ng-click="save()">Save</button>
    <button type="button" class="btn btn-default" ng-click="cancel()">Cancel</button>
</div>