<div class="row">
    <div class="col-sm-12">
        <div class="mkg panel panel-primary">
            <div class="panel-heading">
                <h4>Multi-Key Generator</h4>
            </div>
            <div class="panel-body">
                <form id="mkgForm" name="mkgForm" class="form-horizontal">
                    <fieldset>
                        <legend>Bind Options</legend>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-3 hidden-xs">Numeric Keypad</label>
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <table class="keypad">
                                    <tr class="key-row">
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button" disabled>Num<br/>Lock</button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">/</button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">*</button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">-</button>
                                        </td>
                                    </tr>
                                    <tr class="key-row">
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">7<br/><span class="key-alt-fn">Home</span></button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">8<br/><span class="glyphicon glyphicon-arrow-up key-alt-fn"></span></button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">9<br/><span class="key-alt-fn">Pg Up</span></button>
                                        </td>
                                        <td class="key-cell" rowspan="2">
                                            <button class="btn btn-default key tall-key" type="button">+</button>
                                        </td>
                                    </tr>
                                    <tr class="key-row">
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">4<br/><span class="glyphicon glyphicon-arrow-left key-alt-fn"></span></button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">5</button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">6<br/><span class="glyphicon glyphicon-arrow-right key-alt-fn"></span></button>
                                        </td>
                                    </tr>
                                    <tr class="key-row">
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">1<br/><span class="key-alt-fn">End</span></button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">2<br/><span class="glyphicon glyphicon-arrow-down key-alt-fn"></span></button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">3<br/><span class="key-alt-fn">Pg Dn</span></button>
                                        </td>
                                        <td class="key-cell" rowspan="2">
                                            <button class="btn btn-default key tall-key" type="button">Enter</button>
                                        </td>
                                    </tr>
                                    <tr class="key-row">
                                        <td class="key-cell" colspan="2">
                                            <button class="btn btn-default key wide-key" type="button">0<br/><span class="key-alt-fn">Insert</span></button>
                                        </td>
                                        <td class="key-cell">
                                            <button class="btn btn-default key" type="button">.<br/><span class="key-alt-fn">Delete</span></button>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </fieldset>

                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-8 col-sm-offset-3 col-sm-9">
                            <input id="mkgSubmitBtn" name="mkgSubmitBtn" type="submit" class="btn btn-primary" ng-click="generateBinds()" value="Generate Binds" />
                            <input id="mkgResetBtn" name="mkgResetBtn" type="reset" class="btn btn-default" ng-click="resetBinds()" value="Reset" />
                        </div>
                    </div>
                </form>

            </div>
            <div class="panel-footer" ng-show="buyBinds">
                <h4>Generated Buy Binds:</h4>
                <pre class="buy-binds">{{ buyBinds }}</pre>
            </div>
        </div>
    </div>
</div>