<div class="row">
    <div class="col-sm-12">
        <div class="skg panel panel-primary">
            <div class="panel-heading">
                <h4>Single Key Generator</h4>
            </div>
            <div class="panel-body">
                <form id="skgForm" name="skgForm" class="form-horizontal">
                    <fieldset>
                        <legend>Bind Options</legend>
                        <div class="form-group" ng-class="{ 'has-error': submitted && skgForm.skgKeySelect.$invalid }">
                            <label for="skgKeySelect" class="control-label col-sm-3">Key to Bind</label>
                            <div class="col-sm-9">
                                <select id="skgKeySelect" name="skgKeySelect" class="form-control" ng-model="bindOptions.keyToBind" required>
                                    <option value="">Select a key to bind...</option>
                                    <optgroup ng-repeat="keyGroup in bindableKeys.keyGroups" label="{{ keyGroup.name }}">
                                        <option ng-repeat="bindableKey in keyGroup.keys"
                                                value="{{ bindableKey.bind }}"
                                                ng-selected="bindOptions.keyToBind == bindableKey.bind">{{ bindableKey.name }}</option>
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group" ng-class="{ 'has-error': submitted && skgForm.skgKeySelect.$invalid }">
                            <div class="col-sm-offset-3 col-sm-9">
                                <div class="input-group">
                                    <div class="btn input-group-addon" press-any-key-button on-key-press="setKeyToBindByCode"
                                         inactive-class="btn-default" active-class="btn-info">Press Any Key <span class="glyphicon glyphicon-edit"></span></div>
                                    <div class="form-control" disabled><code ng-show="bindOptions.keyToBind">{{ bindOptions.keyToBind }}</code></div>
                                    <span class="glyphicon glyphicon-remove form-control-feedback" ng-show="submitted && skgForm.skgKeySelect.$invalid"></span>
                                </div>
                                <p class="help-block" ng-show="submitted && skgForm.skgKeySelect.$invalid">* You must select a key to bind!</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="skgPrimaryWeaponSelect" class="control-label col-sm-3">Primary Weapon</label>
                            <div class="col-sm-9">
                                <select id="skgPrimaryWeaponSelect" name="skgPrimaryWeaponSelect" class="form-control" ng-model="bindOptions.primaryWeapon">
                                    <option value="">None</option>
                                    <optgroup ng-repeat="weaponGroup in primaryWeapons.weaponGroups" label="{{ weaponGroup.name }}">
                                        <option ng-repeat="primary in weaponGroup.weapons"
                                                value="{{ primary.bind }}"
                                                ng-selected="bindOptions.primaryWeapon == primary.bind">{{ primary.name }}</option>
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="skgSecondaryWeaponSelect" class="control-label col-sm-3">Secondary Weapon</label>
                            <div class="col-sm-9">
                                <select id="skgSecondaryWeaponSelect" name="skgSecondaryWeaponSelect" class="form-control" ng-model="bindOptions.secondaryWeapon">
                                    <option value="">None</option>
                                    <optgroup ng-repeat="weaponGroup in secondaryWeapons.weaponGroups" label="{{ weaponGroup.name }}">
                                        <option ng-repeat="secondary in weaponGroup.weapons"
                                                value="{{ secondary.bind }}"
                                                ng-selected="bindOptions.secondaryWeapon == secondary.bind">{{ secondary.name }}</option>
                                    </optgroup>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">Gear</label>
                            <div class="col-sm-9">
                                <div ng-repeat="gearItem in gear" class="checkbox checkbox-inline checkbox-inline-no-indent checkbox-not-inline-xs">
                                    <label>
                                        <input name="skgGear[]"
                                               type="checkbox"
                                               value="{{ gearItem.bind }}"
                                               ng-checked="bindOptions.gear.indexOf(gearItem.bind) > -1"
                                               ng-click="toggleGearSelection(gearItem.bind)" /> {{ gearItem.name }}
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-3">Grenades</label>
                            <div class="col-sm-9">
                                <div ng-repeat="grenade in grenades" class="checkbox checkbox-inline checkbox-inline-no-indent checkbox-not-inline-xs">
                                    <label>
                                        <input name="skgGrenades[]"
                                               type="checkbox"
                                               value="{{ grenade.bind }}"
                                               ng-checked="bindOptions.grenades.indexOf(grenade.bind) > -1"
                                               ng-click="toggleGrenadeSelection(grenade.bind)"
                                               ng-disabled="allowExtraGrenade(grenade.bind) && hasExtraGrenadeSelection(grenade.bind)" />
                                        {{ grenade.name }}
                                    </label>
                                    <label ng-show="allowExtraGrenade(grenade.bind)">
                                        ( <input name="skgExtraFlash"
                                                type="checkbox"
                                                class="checkbox-extra"
                                                value="{{ grenade.bind }}"
                                                ng-checked="hasExtraGrenadeSelection(grenade.bind)"
                                                ng-click="toggleExtraGrenadeSelection(grenade.bind)" />
                                        <span class="checkbox-inline-inline-label">&times; 2</span> )
                                    </label>
                                </div>
                            </div>
                        </div>
                    </fieldset>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                            <input id="skgSubmitBtn" name="skgSubmitBtn" type="submit" class="btn btn-primary" ng-click="generateBind(bindOptions)" value="Generate Bind" />
                            <input id="skgResetBtn" name="skgResetBtn" type="reset" class="btn btn-default" ng-click="resetBind()" value="Reset" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer" ng-show="buyBind">
                <button type="button" class="btn btn-info pull-right hidden-xs" clip-copy="buyBind">Copy to Clipboard <span class="glyphicon glyphicon-copy"></span></button>
                <h4>Generated Buy Bind:</h4>
                <pre class="buy-binds">{{ buyBind }}</pre>
                <button type="button" class="btn btn-info visible-xs" clip-copy="buyBind">Copy to Clipboard <span class="glyphicon glyphicon-copy"></span></button>
            </div>
        </div>
    </div>
</div>